### ISSUE TITLE
求教，为什么升级后无法使用了呢？

### ISSUE THREAD

**Issue by shijinsu** [TechXueXi/TechXueXi#105]
D:\QG>set PATH=D:\QG\SourcePackages\chrome;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files (x86)\PuTTY\;C:\Users\shiji\AppData\Local\Microsoft\WindowsApps;C:\adb;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\shiji\AppData\Local\Microsoft\WindowsApps;C:\Users\shiji\AppData\Roaming\npm

D:\QG>set PYTHONPATH=${PYTHONPATH}:D:\QG\SourcePackages

D:\QG>.\SourcePackages\chrome\python\python.exe .\SourcePackages\pandalearning.py
Traceback (most recent call last):
  File ".\SourcePackages\pandalearning.py", line 11, in <module>
    from pdlearn import user
  File "D:\QG\SourcePackages\pdlearn\user.py", line 1, in <module>
    from pdlearn import globalvar
  File "D:\QG\SourcePackages\pdlearn\globalvar.py", line 7, in <module>
    from pdlearn.web import WebHandler
  File "D:\QG\SourcePackages\pdlearn\web.py", line 1, in <module>
    from webserverListener import Message, QrUrl, db
  File "D:\QG\SourcePackages\webserverListener.py", line 11, in <module>
    import pandalearning as pdl
  File "D:\QG\SourcePackages\pandalearning.py", line 20, in <module>
    from pdlearn.answer_question import daily, weekly, zhuanxiang
  File "D:\QG\SourcePackages\pdlearn\answer_question.py", line 14, in <module>
    import pdlearn.globalvar as gl
AttributeError: module 'pdlearn' has no attribute 'globalvar'

D:\QG>pause
请按任意键继续. . .

**Comment by shijinsu** [comment]
> D:\QG>set PATH=D:\QG\SourcePackages\chrome;C:\Program Files\Python37\Scripts;C:\Program Files\Python37;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\dotnet;C:\Program Files (x86)\PuTTY;C:\Users\shiji\AppData\Local\Microsoft\WindowsApps;C:\adb;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Users\shiji\AppData\Local\Microsoft\WindowsApps;C:\Users\shiji\AppData\Roaming\npm
> 
> D:\QG>set PYTHONPATH=${PYTHONPATH}:D:\QG\SourcePackages
> 
> D:\QG>.\SourcePackages\chrome\python\python.exe .\SourcePackages\pandalearning.py Traceback (most recent call last): File ".\SourcePackages\pandalearning.py", line 11, in from pdlearn import user File "D:\QG\SourcePackages\pdlearn\user.py", line 1, in from pdlearn import globalvar File "D:\QG\SourcePackages\pdlearn\globalvar.py", line 7, in from pdlearn.web import WebHandler File "D:\QG\SourcePackages\pdlearn\web.py", line 1, in from webserverListener import Message, QrUrl, db File "D:\QG\SourcePackages\webserverListener.py", line 11, in import pandalearning as pdl File "D:\QG\SourcePackages\pandalearning.py", line 20, in from pdlearn.answer_question import daily, weekly, zhuanxiang File "D:\QG\SourcePackages\pdlearn\answer_question.py", line 14, in import pdlearn.globalvar as gl AttributeError: module 'pdlearn' has no attribute 'globalvar'
> 
> D:\QG>pause 请按任意键继续. . .
