### ISSUE TITLE
Mac 运行源码 selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 91 Current browser version is 95.0.4638.69 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

### ISSUE THREAD

**Issue by fuzhaochen** [TechXueXi/TechXueXi#109]
### 清单

- [x] 我已经仔细阅读过 README.md  ( https://github.com/TechXueXi/TechXueXi/blob/developing/README.md )
- [x] 我已经仔细阅读过 文档  ( https://github.com/TechXueXi/TechXueXi/wiki )
- [x] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [x] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [ ] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**系统版本，包含位数**：macOS 12.0.1 (21A559)

**软件/源码版本**：v20211103版本源码

**浏览器、驱动版本**：Google Chrome 95.0.4638.69 (正式版本) (x86_64)

**python版本**：Python 3.6.5 

**docker版本**：

-----

## 详细描述
答：Mac python3.6环境下运行v20211103源码，不能打开Chrome浏览器（打开一下立马闪退）

## 全部报错
答：

```
============================================================
 Chrome 浏览器初始化失败。信息：

您可以检查下：
1. 是否存在./chrome/chromedriver.exe 或 PATH 中是否存在 chromedriver.exe
2. 浏览器地址栏输入 chrome://version 看到的chrome版本 和 运行 chromedriver.exe 显示的版本整数部分是否相同
针对上述问题，请在 http://npm.taobao.org/mirrors/chromedriver 下载对应版本程序并放在合适的位置
3. 如不是以上问题，请提issue，附上报错信息和您的环境信息
============================================================
按回车键继续......
Exception in thread 开始学xi:
Traceback (most recent call last):
  File "/Users/fuzhao/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/fuzhao/Downloads/TechXueXi-developing/SourcePackages/pdlearn/threads.py", line 44, in run
    self.func(*self.args)
  File "/Users/fuzhao/Downloads/TechXueXi-developing/SourcePackages/pandalearning.py", line 72, in start_learn
    driver_login = Mydriver()
  File "/Users/fuzhao/Downloads/TechXueXi-developing/SourcePackages/pdlearn/mydriver.py", line 126, in __init__
    executable_path=one_path, chrome_options=self.options)
  File "/Users/fuzhao/anaconda3/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/fuzhao/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/fuzhao/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/fuzhao/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/fuzhao/anaconda3/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 91
Current browser version is 95.0.4638.69 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

```

## 建议
答：运行截图如下
![image](https://user-images.githubusercontent.com/71213979/141419562-5ac42fab-5582-400b-b17c-0590135063c0.png)

**Comment by fuzhaochen** [comment]
已解决，感谢[telegram]群里面大神的指导，方法是：到http://npm.taobao.org/mirrors/chromedriver 网站下载与电脑浏览器版本对应的chromedriver文件，解压后放到Mac的/usr/local/bin目录即可。
