### ISSUE TITLE
微信/tgbot模式下日志异常

### ISSUE THREAD

**Issue by Xiaohantx** [TechXueXi/TechXueXi#113]
### 清单

- [ x ] 我已经仔细阅读过 README.md  ( https://github.com/TechXueXi/TechXueXi/blob/developing/README.md )
- [ x ] 我已经仔细阅读过 文档  ( https://github.com/TechXueXi/TechXueXi/wiki )
- [ x ] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [ x ] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [ x ] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**系统版本，包含位数**：macOS 11.6 (20G165) / CentOS 7.7.1908 x86_64(Py3.7.9)

**软件/源码版本**：v20211103

**浏览器、驱动版本**：95.0.4638.69（正式版本） (arm64)

**python版本**：

**docker版本**： 3.6.0 (3.6.0.5487) /  3.6

-----

## 详细描述
答：

在模式为微信或者tg机器人下会报异常，在mac本地和云服务器中均有尝试

## 全部报错
答：

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request

    self._validate_conn(conn)

  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn

    conn.connect()

  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 426, in connect

    tls_in_tls=tls_in_tls,

  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket

    sock, context, tls_in_tls, server_hostname=server_hostname

  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl

    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)

  File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket

    session=session

  File "/usr/local/lib/python3.7/ssl.py", line 870, in _create

    self.do_handshake()

  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake

    self._sslobj.do_handshake()

socket.timeout: _ssl.c:1074: The handshake operation timed out


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send

    timeout=timeout

  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen

    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 532, in increment

    raise six.reraise(type(error), error, _stacktrace)

  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 770, in reraise

    raise value

  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen

./start.sh: line 38: supervisord: command not found

./start.sh: line 41: supervisorctl: command not found

    chunked=chunked,

  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 385, in _make_request

    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)

  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout

    self, url, "Read timed out. (read timeout=%s)" % timeout_value

urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=15)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner

    self.run()

  File "/xuexi/pdlearn/threads.py", line 44, in run

    self.func(*self.args)

  File "/xuexi/pandalearning.py", line 67, in start_learn

    gl.pushprint(msg, chat_id=uid)

  File "/xuexi/pdlearn/globalvar.py", line 111, in pushprint

    tg_bot.send_message(text)

  File "/xuexi/pdlearn/telegram.py", line 20, in send_message

    self.bot.send_message(self.master, message)

  File "/usr/local/lib/python3.7/site-packages/telebot/__init__.py", line 928, in send_message

    entities, allow_sending_without_reply))

  File "/usr/local/lib/python3.7/site-packages/telebot/apihelper.py", line 257, in send_message

    return _make_request(token, method_url, params=payload, method='post')

  File "/usr/local/lib/python3.7/site-packages/telebot/apihelper.py", line 141, in _make_request

    timeout=(connect_timeout, read_timeout), proxies=proxy)

  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request

    resp = self.send(prep, **send_kwargs)

  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send

    r = adapter.send(request, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send

    raise ReadTimeout(e, request=request)

requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=15)
```

## 建议
答：

**Comment by Stdocdure** [comment]
我也遇到了同样的问题，tgbot 经常抽风不知道什么缘故。

**Comment by techxuexi21** [comment]
@Stdocdure requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=15)
一般是梯子问题。梯子一断就报这，机器人如果不用 supervisord守护就掉线
