### ISSUE TITLE
mac 下出现执行问题

### ISSUE THREAD

**Issue by chenbokaix250** [TechXueXi/TechXueXi#114]
python3 ./pandalearning.py
============================================================
    我们的网站，GitHub 等页面已经被中国大陆的浏览器加入黑名单，请用谷歌浏览器 chrome 打开我们的站点。
    科技强 guo 官方网站：https://techxuexi.js.org
    Github地址：https://github.com/TechXueXi
使用本项目，必须接受以下内容，否则请立即退出：
    - TechXueXi 仅额外提供给“爱党爱 guo ”且“工作学业繁重”的人
    - 项目开源协议 LGPL-3.0
    - 不得利用本项目盈利
另外，我们建议你参与一个维护劳动法的项目：
https://996.icu/ 或 https://github.com/996icu/996.ICU/blob/master/README_CN.md
============================================================
TechXueXi 现支持以下模式（答题时请值守电脑旁处理少部分不正常的题目）：
--------------------------------------
0 仅登录
1 文章+视频
2           每日答题+每周答题+专项答题
3 文章+视频+每日答题+每周答题+专项答题
4 更改默认用户
5 查看所有用户今日得分情况
6 刷新所有用户登录状态为最新
============================================================
开启： 获取更新信息...
[*] 正在联网获取更新信息...(更新显示不会打断之前输入等操作)
开启： 开始学xi
是否无头模式：False None
当前选择模式：3
============================================================
需要增加新用户，请扫码登录，否则请无视
需要增加新用户，请扫码登录，否则请无视
============================================================
 Chrome 浏览器初始化失败。信息：
可找到 "./chrome/chrome.exe"
您可以检查下：
1. 是否存在./chrome/chromedriver.exe 或 PATH 中是否存在 chromedriver.exe
2. 浏览器地址栏输入 chrome://version 看到的chrome版本 和 运行 chromedriver.exe 显示的版本整数部分是否相同
针对上述问题，请在 http://npm.taobao.org/mirrors/chromedriver 下载对应版本程序并放在合适的位置
3. 如不是以上问题，请提issue，附上报错信息和您的环境信息
============================================================
按回车键继续......[*] TechXueXi最新下载地址为 https://github.com/TechXueXi/TechXueXi
[*] 程序版本为：v20211015
[*] 最新版本为：v20211103
[*] 当前不是最新版本，建议更新
[*] ============================================================
[*] 更新提要：
[*] v20211103
docker: techxuexi web 推送优化。取消docker自动更新的代码。利用更新信息的文件，查询本地版本能否使用的功能。冲突处理，webui优化，更新Dockerfile_arm32v7，Dockerfile_arm64v8
[*] v20211102
docker: 修复微信子账号登录问题，增加list,update指令,techxuexi web 推送优化。
[*] v20211101
docker: 1. 部分功能采用及时回复; 2. 微信模板发送; 3. 增加微信模板配置项，增加说明文档
[*] v20211031
docker: 1.增加微信互动功能; 2.微信token改为文件存储，方便主线程和守护线程共享; 3.修改bot消息发送，可以发送给指定用户; 4.增加文档说明; 5.增加默认配置文件的配置项; 6.微信暂时使用nohup启动，方便查阅日志，稳定后改为supervisord; 7.修复文档，get_score异常处理; 8.access_token过期后强制刷新;
[*] v20211030
优化参数配置 修复了无窗模式默认开启的问题，优化v指令
[*] v20211029
docker增加了web 推送支持。
[*] v20211028
docker增加了一个自循环方法，如果出现连接超时问题，就自己再次启动连接。
[*] v20211027
增加收集题库配置项，修复提示异常，增加全局消息
[*] v20211025
Docker enable supervisor，修改文档
[*] v20211022
fix refresh cookie error，修复q_text 使用异常，修改 mydriver.py 初始化参数，同步更新tgbot监听功能，更新上传题目地址
[*] v20211018
增加tg代理配置项。修复SendLoginQRcode的错误提示。取消自动打包arm32v7 docker（存在问题）。修改requirements.txt
[*] v20211017
适配armv7 32位docker
[*] TechXueXi最新下载地址为 https://github.com/TechXueXi/TechXueXi
[*] 科技强国官方网站：https://techxuexi.js.org

Exception in thread 开始学xi:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/bokaichen/Downloads/techxuexi-v20211020/SourcePackages/pdlearn/threads.py", line 44, in run
    self.func(*self.args)
  File "./pandalearning.py", line 71, in start_learn
    driver_login = Mydriver()
  File "/Users/bokaichen/Downloads/techxuexi-v20211020/SourcePackages/pdlearn/mydriver.py", line 120, in __init__
    self.driver = self.webdriver.Chrome(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './chrome/chromedriver.exe'

**Comment by chenbokaix250** [comment]
Exception in thread 开始学xi:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './chrome/chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/bokaichen/Downloads/techxuexi-v20211020/SourcePackages/pdlearn/threads.py", line 44, in run
    self.func(*self.args)
  File "pandalearning.py", line 71, in start_learn
    driver_login = Mydriver()
  File "/Users/bokaichen/Downloads/techxuexi-v20211020/SourcePackages/pdlearn/mydriver.py", line 120, in __init__
    self.driver = self.webdriver.Chrome(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home





---

 then i use chmod 775 to change permission of ./chrome/chromedriver.exe

how can i solve this problem

**Comment by techxuexi21** [comment]
@chenbokaix250 这个能否解决 https://github.com/TechXueXi/TechXueXi/issues/109#issuecomment-967792140

**Comment by techxuexi21** [comment]
@chenbokaix250 注意 Mac 不会运行 chromedriver.exe ，要重新下载

**Comment by chenbokaix250** [comment]
> #109 (comment)

已经将这个LASTER_XXX 文件放在里面 但是未解决

> @chenbokaix250 注意 Mac 不会运行 chromedriver.exe ，要重新下载

这块有点不明白 您讲的是将Sourcepackage下的chrome全部替换 还是只将chromedriver.exe  替换为chromedriver这个文件

尝试过替换chromedriver.exe后 出现错误：
selenium.common.exceptions.WebDriverException: Message: unknown error: Failed to create Chrome process.

**Comment by chenbokaix250** [comment]
我应该是下载了windows版本的代码 搞错了
