### ISSUE TITLE
在 MacBook M1 上使用 docker 启动程序遇到 supervisord supervisorctl command not found 问题

### ISSUE THREAD

**Issue by UnfoldeParallel** [TechXueXi/TechXueXi#115]
### 清单

- [x] 我已经仔细阅读过 README.md  ( https://github.com/TechXueXi/TechXueXi/blob/developing/README.md )
- [x] 我已经仔细阅读过 文档  ( https://github.com/TechXueXi/TechXueXi/wiki )
- [x] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [x] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [x] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**系统版本，包含位数**：macOS Monterey 12.0.1 on MacBook Air (M1, 2020)

**软件/源码版本**：v20211103

**docker版本**：Docker version 20.10.10, build b485636

-----
## 详细描述
答：尝试通过docker启动ARM版程序，启动过程中提示 `supervisord command not found `  ，启动后无法访问 http://127.0.0.1:9980 。 使用类似方法，在另一台 x86 MacBook 上启动 x86 版程序，没有这个问题。

## 全部报错
答：

```
$ docker run \
  -ti --rm \
  --name=techxuexi-web \
  --shm-size="2g" \
  -e "ZhuanXiang=True" \
  -e "Pushmode=6" \
  -p "9980:80" \
  docker.mirror.aliyuncs.com/techxuexi/techxuexi-arm64v8

当前模式为网页控制台模式，即将启动守护 --  xuexiweb
./start.sh: line 50: supervisord: command not found
./start.sh: line 55: supervisorctl: command not found
开始运行
============================================================
    我们的网站，GitHub 等页面已经被中国大陆的浏览器加入黑名单，请用谷歌浏览器 chrome 打开我们的站点。
    科技强 guo 官方网站：https://techxuexi.js.org
    Github地址：https://github.com/TechXueXi
使用本项目，必须接受以下内容，否则请立即退出：
    - TechXueXi 仅额外提供给“爱党爱 guo ”且“工作学业繁重”的人
    - 项目开源协议 LGPL-3.0
    - 不得利用本项目盈利
另外，我们建议你参与一个维护劳动法的项目：
https://996.icu/ 或 https://github.com/996icu/996.ICU/blob/master/README_CN.md
============================================================
TechXueXi 现支持以下模式（答题时请值守电脑旁处理少部分不正常的题目）：
--------------------------------------
0 仅登录
1 文章+视频
2           每日答题+每周答题+专项答题
3 文章+视频+每日答题+每周答题+专项答题
4 更改默认用户
5 查看所有用户今日得分情况
6 刷新所有用户登录状态为最新
============================================================
开启： 获取更新信息...
[*] 正在联网获取更新信息...(更新显示不会打断之前输入等操作)
开启： 开始学xi
是否无头模式：True True

需要增加新用户，请扫码登录，否则请无视

web模式跳过自动获取二维码,请手动点击添加按钮
【#️⃣】 若直接退出请运行：webserverListener.py
欢迎使用 TechXueXi
[*] TechXueXi最新下载地址为 https://github.com/TechXueXi/TechXueXi
[*] 程序版本为：v20211103
[*] 最新版本为：v20211103
```

**Comment by techxuexi21** [comment]
@UnfoldeParallel arm64 请先拉最新 dev 的 docker 版本， docker tag 为 dev82 。

**Comment by UnfoldeParallel** [comment]
@techxuexi21 你好，我尝试了https://hub.docker.com/r/techxuexi/techxuexi-arm64v8/tags 列的 `dev83` , `developing82`, `dev81` 等 tags，都出现了类似问题，启动过程中提示 `./start.sh: line 70: /xuexi/user/web_listener.log: No such file or directory` ，仍然无法访问 http://127.0.0.1:9980 。以 dev83 为例，错误日志如下：


```
$ docker run \
  -ti --rm \
  --name=techxuexi-web \
  --shm-size="2g" \
  -e "ZhuanXiang=True" \
  -e "Pushmode=6" \
  -p "9980:80" \
 techxuexi/techxuexi-arm64v8:dev83

当前模式为 WEB网页控制台 模式，即将启动守护 --  xuexiweb
./start.sh: line 70: /xuexi/user/web_listener.log: No such file or directory
Error: Source contains parsing errors: '/etc/supervisord.conf'
        [line 179]: 'stderr_logfile/xuexi/user/wechat_listener.log\n'
        [line 189]: 'stderr_logfile/xuexi/user/tg_listener.log\n'
        [line 199]: 'stderr_logfile/xuexi/user/web_listener.log\n'
For help, use /usr/bin/supervisord -h
Traceback (most recent call last):
  File "/usr/bin/supervisorctl", line 33, in <module>
    sys.exit(load_entry_point('supervisor==4.2.2', 'console_scripts', 'supervisorctl')())
  File "/usr/lib/python3/dist-packages/supervisor/supervisorctl.py", line 1406, in main
    options.realize(args, doc=__doc__)
  File "/usr/lib/python3/dist-packages/supervisor/options.py", line 1678, in realize
    Options.realize(self, *arg, **kw)
  File "/usr/lib/python3/dist-packages/supervisor/options.py", line 310, in realize
    self.process_config()
  File "/usr/lib/python3/dist-packages/supervisor/options.py", line 318, in process_config
    self.process_config_file(do_usage)
  File "/usr/lib/python3/dist-packages/supervisor/options.py", line 348, in process_config_file
    self.read_config(self.configfile)
  File "/usr/lib/python3/dist-packages/supervisor/options.py", line 1699, in read_config
    parser.read_file(fp)
  File "/usr/lib/python3.9/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.9/configparser.py", line 1113, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '/etc/supervisord.conf'
        [line 179]: 'stderr_logfile/xuexi/user/wechat_listener.log\n'
        [line 189]: 'stderr_logfile/xuexi/user/tg_listener.log\n'
        [line 199]: 'stderr_logfile/xuexi/user/web_listener.log\n'
守护进程启动失败，切换备用方式
./start.sh: line 77: /xuexi/user/web_listener.log: No such file or directory
tail: cannot open '/xuexi/user/web_listener.log' for reading: No such file or directory
tail: no files remaining
开始运行
============================================================
    我们的网站，GitHub 等页面已经被中国大陆的浏览器加入黑名单，请用谷歌浏览器 chrome 打开我们的站点。
    科技强 guo 官方网站：https://techxuexi.js.org
    Github地址：https://github.com/TechXueXi
使用本项目，必须接受以下内容，否则请立即退出：
    - TechXueXi 仅额外提供给“爱党爱 guo ”且“工作学业繁重”的人
    - 项目开源协议 LGPL-3.0
    - 不得利用本项目盈利
另外，我们建议你参与一个维护劳动法的项目：
https://996.icu/ 或 https://github.com/996icu/996.ICU/blob/master/README_CN.md
============================================================
TechXueXi 现支持以下模式（答题时请值守电脑旁处理少部分不正常的题目）：
--------------------------------------
0 仅登录
1 文章+视频
2           每日答题+每周答题+专项答题
3 文章+视频+每日答题+每周答题+专项答题
4 更改默认用户
5 查看所有用户今日得分情况
6 刷新所有用户登录状态为最新
============================================================
开启： 获取更新信息...
[*] 正在联网获取更新信息...(更新显示不会打断之前输入等操作)
开启： 开始学xi
是否无头模式：True True

需要增加新用户，请扫码登录，否则请无视

web模式跳过自动获取二维码,请手动点击添加按钮
【#️⃣】 若直接退出请运行：webserverListener.py
欢迎使用 TechXueXi
[*] TechXueXi最新下载地址为 https://github.com/TechXueXi/TechXueXi
[*] 程序版本为：v20211112
[*] 最新版本为：v20211103
```

**Comment by ioslonghua** [comment]
Arm64也是遇到这个情况

**Comment by techxuexi21** [comment]
@ioslonghua 应该是缺依赖包，进 docker 安装。具体谷歌，可以参考最新的 dockerfile  里的命令

**Comment by UnfoldeParallel** [comment]
这个问题在 dev84 版本解决了，非常感谢！

```
$ docker run \
  -ti --rm \                                                                           
  --name=techxuexi-web \                                                               
  --shm-size="2g" \                                                                                                                                                           
  -e "ZhuanXiang=True" \                                                                                                                                                      
  -e "Pushmode=6" \                                                                                                                                                           
  -p "9980:80" \                                                                                                                                                              
 techxuexi/techxuexi-arm64v8:dev84  
```

**Comment by Leoin1** [comment]
最新的latest的不知道修复此问题没有

**Comment by techxuexi21** [comment]
@Leoin1 修了，还不行再提issue

**Comment by Leoin1** [comment]
> 用的是 techxuexi/techxuexi-arm64v8:dev84  
我的设备是树莓派4B 系统Diet-Pi的
TAG为latest的还是显示这个问题，并且无法更新代码。据说更新跳转的github链接被墙
刚看到Arm64下的Dockerfile有更新，试一下dev:86

**Comment by Leoin1** [comment]
试了一下dev:86 我无法拉取 求解决办法
