### ISSUE TITLE
Chromedriver

### ISSUE THREAD

**Issue by zhasamwu45** [TechXueXi/TechXueXi#125]
### 清单

- [√ ] 我已经仔细阅读过 README.md  ( https://github.com/TechXueXi/TechXueXi/blob/developing/README.md )
- [ √] 我已经仔细阅读过 文档  ( https://github.com/TechXueXi/TechXueXi/wiki )
- [ √] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [√ ] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [x] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**系统版本，包含位数**：mac12.0.1 64bit

**软件/源码版本**：v20211128

**浏览器、驱动版本**：96.0.4664.93 (正式版本) (x86_64)

**python版本**：3.9

**docker版本**：

-----

## 详细描述
答：chromedriver今天运行不了。前几天都可以

## 全部报错
答：您可以检查下：
1. 是否存在./chrome/chromedriver.exe 或 PATH 中是否存在 chromedriver.exe
2. 浏览器地址栏输入 chrome://version 看到的chrome版本 和 运行 chromedriver.exe 显示的版本整数部分是否相同
针对上述问题，请在 http://npm.taobao.org/mirrors/chromedriver 下载对应版本程序并放在合适的位置
3. 如不是以上问题，请提issue，附上报错信息和您的环境信息

报错信息： Chrome 浏览器初始化失败。信息：

都不是以上问题，已经尝试过brew install Chromedriver，手动替换等。也是不行的。
## 建议
答：

**Comment by 4674ghkbvgy** [comment]
同样报错

```
sudo python3 ./pandalearning.py
[sudo]  xxx的密码：
============================================================
    我们的网站，GitHub 等页面已经被中国大陆的浏览器加入黑名单，请用谷歌浏览器 chrome 打开我们的站点。
    科技强 guo 官方网站：https://techxuexi.js.org
    Github地址：https://github.com/TechXueXi
使用本项目，必须接受以下内容，否则请立即退出：
    - TechXueXi 仅额外提供给“爱党爱 guo ”且“工作学业繁重”的人
    - 项目开源协议 LGPL-3.0
    - 不得利用本项目盈利
另外，我们建议你参与一个维护劳动法的项目：
https://996.icu/ 或 https://github.com/996icu/996.ICU/blob/master/README_CN.md
============================================================
============================================================
TechXueXi 现支持以下模式（答题时请值守电脑旁处理少部分不正常的题目）：
--------------------------------------
0 仅登录
1 文章+视频
2           每日答题+每周答题+专项答题
3 文章+视频+每日答题+每周答题+专项答题
4 更改默认用户
5 查看所有用户今日得分情况
6 刷新所有用户登录状态为最新
============================================================
开启： 获取更新信息...
[*] 正在联网获取更新信息...(更新显示不会打断之前输入等操作)
开启： 开始学xi
是否无头模式：False None
当前选择模式：3
============================================================
需要增加新用户，请扫码登录，否则请无视
欢迎使用 TechXueXi
[*] TechXueXi最新下载地址为 https://github.com/TechXueXi/TechXueXi
[*] 程序版本为：v20211103
[*] 最新版本为：v20211103
============================================================
 Chrome 浏览器初始化失败。信息：
可找到 "/opt/google/chrome/chrome"
您可以检查下：
1. 是否存在./chrome/chromedriver.exe 或 PATH 中是否存在 chromedriver.exe
2. 浏览器地址栏输入 chrome://version 看到的chrome版本 和 运行 chromedriver.exe 显示的版本整数部分是否相同
针对上述问题，请在 http://npm.taobao.org/mirrors/chromedriver 下载对应版本程序并放在合适的位置
3. 如不是以上问题，请提issue，附上报错信息和您的环境信息
============================================================
按回车键继续......
Exception in thread 开始学xi:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/TechXueXi-20211103/SourcePackages/pdlearn/threads.py", line 44, in run
    self.func(*self.args)
  File "./pandalearning.py", line 72, in start_learn
    driver_login = Mydriver()
  File "/home/TechXueXi-20211103/SourcePackages/pdlearn/mydriver.py", line 127, in __init__
    self.driver = self.webdriver.Chrome(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /snap/chromium/1827/usr/lib/chromium-browser/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```
系统：ubuntu20.04
浏览器、驱动版本相同：96.0.4664.45

试过这个
https://github.com/TechXueXi/TechXueXi/issues/5#issuecomment-932674963
链接中的方法，两种都没解决

**Comment by fdq236** [comment]
您好，我已收到您发的邮件！待我看后回复！谢谢啦！
                                                                      pcq泉
