### ISSUE TITLE
baocuo

### ISSUE THREAD

**Issue by xiaoqiqiya** [TechXueXi/TechXueXi#126]
### 清单

- [x] 我已经仔细阅读过 README.md  ( https://github.com/TechXueXi/TechXueXi/blob/developing/README.md )
- [ ] 我已经仔细阅读过 文档  ( https://github.com/TechXueXi/TechXueXi/wiki )
- [ ] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [ ] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [ ] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**系统版本，包含位数**：linux 

**软件/源码版本**：

**浏览器、驱动版本**：

**python版本**：

**docker版本**：  docker

-----

## 详细描述
答：During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/xuexi/pdlearn/threads.py", line 44, in run
    self.func(*self.args)
  File "/xuexi/pandalearning.py", line 79, in start_learn
    uid = user.get_userId(cookies)
  File "/xuexi/pdlearn/user.py", line 18, in get_userId
    userId, total, scores, userName = score.get_score(cookies)
  File "/xuexi/pdlearn/score.py", line 87, in get_score
    headers={'Cache-Control': 'no-cache'}).content.decode("utf8")
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pc-proxy-api.xuexi.cn', port=443): Max retries exceeded with url: /api/score/days/listScoreProgress?sence=score&deviceType=2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe865f87c50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

## 全部报错
答：

```
私はChina を愛しています
```

## 建议
答：

**Comment by yangrunos** [comment]
[自动回复]您好，资料已收到，我会尽快回复您。
