### ISSUE TITLE
已安装requirements.txt中的依赖包，但运行仍然报错

### ISSUE THREAD

**Issue by zgjssyjw** [TechXueXi/TechXueXi#141]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

源码运行

### 软件/源码版本

v20211221

### 系统版本，包含位数

win11 x64 教育版

### 浏览器、驱动版本

97.0.4692.71

### python版本

Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] 

### docker tag版本

未使用docker

### 推送方式

不使用或不开启推送

### 详细描述

`Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\site-packages\pyzbar\zbar_library.py", line 58, in load
    dependencies, libzbar = load_objects(Path(''))
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\site-packages\pyzbar\zbar_library.py", line 52, in load_objects
    for dep in dependencies
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\site-packages\pyzbar\zbar_library.py", line 52, in <listcomp>
    for dep in dependencies
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/jiangwei/Documents/python_code/TechXueXi-20211221/SourcePackages/pandalearning.py", line 12, in <module>
    from pdlearn import globalvar as gl
  File "d:\jiangwei\Documents\python_code\TechXueXi-20211221\SourcePackages\pdlearn\globalvar.py", line 4, in <module>
    from pdlearn.dingding import DingDingHandler
  File "d:\jiangwei\Documents\python_code\TechXueXi-20211221\SourcePackages\pdlearn\dingding.py", line 7, in <module>
    from pyzbar import pyzbar
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\site-packages\pyzbar\pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\site-packages\pyzbar\wrapper.py", line 143, in <module>
    c_uint_p,    # minor
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\site-packages\pyzbar\wrapper.py", line 136, in zbar_function
    return prototype((fname, load_libzbar()))
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\site-packages\pyzbar\wrapper.py", line 115, in load_libzbar
    libzbar, dependencies = zbar_library.load()
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\site-packages\pyzbar\zbar_library.py", line 60, in load
    dependencies, libzbar = load_objects(Path(__file__).parent)
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\site-packages\pyzbar\zbar_library.py", line 54, in load_objects
    libzbar = cdll.LoadLibrary(str(directory.joinpath(fname)))
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "D:\ProgramData\Anaconda3\envs\xuexi\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。`

Visual C++ Redistributable for Visual Studio 2015我是安装了的。
现在把python的版本改成3.7.11，问题依然存在不知道是什么原因，以前在win10上面都没有问题的，难道是win11的原因？？？

**Comment by SnapdragonLee** [comment]
Anaconda的话建议 Python 3.7-3.8，再就是缺少C++环境，都可以试试看

**Comment by arenekosreal** [comment]
从文件地址来看运行脚本的时候似乎启用的是 Anaconda 环境，请确认`requirements.txt`的内容是安装在这个激活的 Anaconda 环境里面。

**Comment by DoveBoy** [comment]
同样的问题，用的Python 3.10.2 Win10正常，Win11专业工作站版报错，也是这个错误

**Comment by DoveBoy** [comment]
问题已经解决了，安装一下vc全家桶就正常了

**Comment by mayjack0312** [comment]
少运行库
估计是程序没链接到动态链接库上去
