### ISSUE TITLE
docker不推送二维码

### ISSUE THREAD

**Issue by kaikaimj** [TechXueXi/TechXueXi#200]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

Docker运行

### 软件/源码版本

v20211221

### 系统版本，包含位数

win10 x64

### 浏览器、驱动版本

chrome 104.0.5112.79

### python版本

python3.6.8 x32（不明，使用默认版本）

### docker tag版本

latest

### 推送方式

4 pluspush

### 详细描述

无论使用何种推送方式，只会收到一条“需要增加新用户，请扫码登录，否则请无视”，但不会接受到任何二维码或者跳转链接。附上docker日志：
开始运行
============================================================
    我们的网站，GitHub 等页面已经被中国大陆的浏览器加入黑名单，请用谷歌浏览器 chrome 打开我们的站点。
    科技强 guo 官方网站：https://techxuexi.js.org
    Github地址：https://github.com/TechXueXi
使用本项目，必须接受以下内容，否则请立即退出：
    - TechXueXi 仅额外提供给“爱党爱 guo ”且“工作学业繁重”的人
    - 项目开源协议 LGPL-3.0
    - 不得利用本项目盈利
另外，我们建议你参与一个维护劳动法的项目：
https://996.icu/ 或 https://github.com/996icu/996.ICU/blob/master/README_CN.md[0m
[0m============================================================[0m [0m
TechXueXi 现支持以下模式（答题时请值守电脑旁处理少部分不正常的题目）：[0m
[0m--------------------------------------

0 仅登录

1 文章+视频

2           每日答题+每周答题+专项答题

3 文章+视频+每日答题+每周答题+专项答题

4 更改默认用户

5 查看所有用户今日得分情况

6 刷新所有用户登录状态为最新
============================================================[0m
[0m开启： 获取更新信息...[0m
[0m[33m[*] 正在联网获取更新信息...(更新显示不会打断之前输入等操作)[39m[0m
[0m开启： 开始学xi[0m
[0m是否无头模式：True True[0m
[0m18bea6ececb848f9b14c5027bf35a597[0m [0m[0m
[0m{"code":200,"msg":"请求成功","data":"aaba853aa1154f59aa671d5589225ec9","count":null}[0m
[0m需要增加新用户，请扫码登录，否则请无视[0m
[0m[33m[*] 版本信息网络错误[39m[0m
[0m[33m[*] 查询本版本是否能继续使用，错误[39m[0m
[0m[33m[*] 版本信息网络错误[39m[0m
[0m============================================================[0m
[0m Chrome 浏览器初始化失败。信息：[0m
[0m[0m
[0m您可以检查下：[0m
[0m1. 是否存在./chrome/chromedriver.exe 或 PATH 中是否存在 chromedriver.exe[0m
[0m2. 浏览器地址栏输入 chrome://version 看到的chrome版本 和 运行 chromedriver.exe 显示的版本整数部分是否相同[0m
[0m针对上述问题，请在 http://npm.taobao.org/mirrors/chromedriver 下载对应版本程序并放在合适的位置[0m
[0m3. 如不是以上问题，请提issue，附上报错信息和您的环境信息[0m
[0m============================================================[0m
Exception in thread 开始学xi:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/xuexi/pdlearn/threads.py", line 44, in run
    self.func(*self.args)
  File "/xuexi/pandalearning.py", line 72, in start_learn
    driver_login = Mydriver()
  File "/xuexi/pdlearn/mydriver.py", line 126, in __init__
    executable_path=one_path, chrome_options=self.options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable

[0m

**Comment by Fireselector** [comment]
我今天也出现一样的问题，求解决

**Comment by wangc39** [comment]
请问，我这个是通过微信来布置的，但是app已经没有一对一的聊天框。无法通过链接登录，这个问题要如何解决呢？

**Comment by Xav1erSue** [comment]
+1

**Comment by kairui1108** [comment]
@Xav1erSue 🇸🇸
