### ISSUE TITLE
Docker 微信推送配置失败

### ISSUE THREAD

**Issue by wxyhgk** [TechXueXi/TechXueXi#208]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

Docker运行

### 软件/源码版本

最新版

### 系统版本，包含位数

ubuntu 20.04

### 浏览器、驱动版本

苹果浏览器

### python版本

python 3.10

### docker tag版本

latest

### 推送方式

2 微信

### 详细描述

* 服务器放行了 8088 端口

* 这里的 8088 端口已经从 docker 映射出来了
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/37659181/204129149-9be43e09-e3b6-4878-a4ad-f1c4e07e2106.png">

* appID 什么的都配置了
<img width="739" alt="image" src="https://user-images.githubusercontent.com/37659181/204129207-c618eca1-3e20-4628-a300-c2f79e920424.png">

最后配置失败了,不知道哪错了
<img width="913" alt="image" src="https://user-images.githubusercontent.com/37659181/204129256-d0ddb500-4f62-48a7-9a88-8df51e3c06fc.png">

**Comment by ruike-kj** [comment]
老哥，你解决了吗？我也偶一样的问题，不知道啥原因

**Comment by kefanlee** [comment]
微信我的也报错

**Comment by mzwkkk** [comment]
先访问下URL试试8088容易被运营商屏蔽。

**Comment by wxyhgk** [comment]
> 先访问下URL试试8088容易被运营商屏蔽。

这个用的国外的服务器按道理应该没问题才对

**Comment by ruike-kj** [comment]
> 先访问下URL试试8088容易被运营商屏蔽。
我的网址打不开，用的腾讯云，而且docker日志有错误
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by GnaixEuy** [comment]
并不是bug哦，检测一下具体的防火墙之类的，我docker微信的方式一直可以用

**Comment by dreamren** [comment]
+1，容器内端口就没能监听起来。
Traceback (most recent call last):
  File "/xuexi/wechatListener.py", line 20, in <module>
    wechat = WechatHandler()
  File "/xuexi/pdlearn/wechat.py", line 12, in __init__
    self.token = self.get_access_token()
  File "/xuexi/pdlearn/wechat.py", line 37, in get_access_token
    expires = int(res.get('expires_in'))-10+time.time()
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by crossgg** [comment]
国外VPS，armv8,dev89镜像，也是一样的错误日志
```
Traceback (most recent call last):
  File "/xuexi/wechatListener.py", line 20, in <module>
    wechat = WechatHandler()
  File "/xuexi/pdlearn/wechat.py", line 12, in __init__
    self.token = self.get_access_token()
  File "/xuexi/pdlearn/wechat.py", line 37, in get_access_token
    expires = int(res.get('expires_in'))-10+time.time()
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by franciswan47** [comment]
我也是这个问题，防火墙都已经放行了，就是不知道程序监听怎么看进程，执行那个命令的时候就是找不到文件

**Comment by kefanlee** [comment]
那你试试直接用docker compose部署







                       
原始邮件
                       
                     

发件人："franciswan47"< ***@***.*** &gt;;

发件时间：2023/2/10 15:30

收件人："TechXueXi/TechXueXi"< ***@***.*** &gt;;

抄送人："Ke.Fan"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [TechXueXi/TechXueXi] Docker 微信推送配置失败 (Issue #208)




 
我也是这个问题，防火墙都已经放行了，就是不知道程序监听怎么看进程，执行那个命令的时候就是找不到文件
 
&mdash;
