### ISSUE TITLE
文章学 xi 检测到异常：list index out of range

### ISSUE THREAD

**Issue by Qcapt** [TechXueXi/TechXueXi#215]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

Docker运行

### 软件/源码版本

v20220126

### 系统版本，包含位数

ubuntu docker

### 浏览器、驱动版本

docker

### python版本

docker

### docker tag版本

latest

### 推送方式

2 微信

### 详细描述

林林总总解决了交换每周专项地址、滑块验证等问题，目前techxuexi运行正常，但只有每天文章学习为0，查日志看到报错为：
`文章学 xi 检测到异常：list index out of range`
看到有个issue同样存在文章学习不完全问题，不过我这一篇都不学，求解决办法

**Comment by hfzh06** [comment]
我从昨天开始文章和视频学习都不能正常完成，视频貌似不能够打开。

**Comment by LizzieOneDay** [comment]
我也是，视频无法学习

**Comment by diaodeng** [comment]
我的视频不能学习，修改这个文件pdlearn.get_links.py的get_video_links方法
```
        video_json = requests.get(
            "https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json").content.decode(
            "utf8")
        video = json.loads(video_json)["DataSet"]
        json_urls = []
        for i in video:
            json_urls.append("https://www.xuexi.cn/lgdata/" + i.split('!')[1])

        all_video_object = []
        for url in json_urls:
            choose_json_str = requests.get(url).content.decode("utf8")
            all_video_object.extend(json.loads(choose_json_str))
        new_list = sorted(all_video_object, key=lambda x: x.get("publishTime", "0"), reverse=False)
        return [news["url"] for news in new_list]
```

![image](https://user-images.githubusercontent.com/108243171/217176837-da281543-a7f4-4b44-94a4-3f6d26c89bea.png)

**Comment by hujinhu** [comment]
你的文章学习有问题吗?  上面的get_article_links方法能看一下吗.

**Comment by hfzh06** [comment]
> 我的视频不能学习，修改这个文件pdlearn.get_links.py的get_video_links方法
> 
> ```
>     video_json = requests.get(
>         "https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json").content.decode(
>         "utf8")
>     video = json.loads(video_json)["DataSet"]
>     json_urls = []
>     for i in video:
>         json_urls.append("https://www.xuexi.cn/lgdata/" + i.split('!')[1])
> 
>     all_video_object = []
>     for url in json_urls:
>         choose_json_str = requests.get(url).content.decode("utf8")
>         all_video_object.extend(json.loads(choose_json_str))
>     new_list = sorted(all_video_object, key=lambda x: x.get("publishTime", "0"), reverse=False)
>     return [news["url"] for news in new_list]
> ```
> 
> ![image](https://user-images.githubusercontent.com/108243171/217176837-da281543-a7f4-4b44-94a4-3f6d26c89bea.png)

感谢，我去修改尝试下

**Comment by diaodeng** [comment]
> 你的文章学习有问题吗? 上面的get_article_links方法能看一下吗.

我的文章没问题，文件get_links.py这样改应该是文章和视频都可以，原来文章的获取地址中的内容没更新了

```
import logging as logger 

import requests
import re
import random
import json


def _get_links(base_url):
    news_url_json = requests.get(base_url).content.decode(
        "utf8")
    news_url = json.loads(news_url_json)["DataSet"]
    json_urls = []
    for i in news_url:
        json_urls.append("https://www.xuexi.cn/lgdata/" + i.split('!')[1])

    all_news_object = []
    for url in json_urls:
        choose_json_str = requests.get(url).content.decode("utf8")
        all_news_object.extend(json.loads(choose_json_str))
    new_list = sorted(all_news_object, key=lambda x: x.get("publishTime", "0"), reverse=False)
    return [news["url"] for news in new_list]


def get_article_links():
    try:
        return _get_links("https://www.xuexi.cn/lgdata/896bddc5f57a423b857a85eb40f98945/72742e3e40c96ade71e42b6e7ed42419.json")
        # 下面获取文章的地址中文章没有继续更新，导致后面无法完成文章学习
        # article = requests.get(
        #     "https://www.xuexi.cn/c06bf4acc7eef6ef0a560328938b5771/data9a3668c13f6e303932b5e0e100fc248b.js").content.decode(
        #     "utf8")
        # pattern = r"list\"\:(.+),\"count\"\:"
        # links = []
        # list = eval(re.search(pattern, article).group(1))[:20000]
        # list.reverse()
        # for i in range(len(list)):
        #     links.append(list[i]["static_page_url"])
        # return links
    except:
        logger.info("=" * 60)
        logger.info("get_article_links获取失败")
        logger.info("=" * 60)
        raise


def get_video_links():
    try:
        return _get_links("https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json")

        # 下面的方法只获取了20个地址返回，且是随机获取的，返回的地址可能有之前用过的，不能保证学习满积分
        # video_json = requests.get("https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json").content.decode("utf8")
        # video=json.loads(video_json)["DataSet"]
        # json_urls = []
        # link = []
        # for i in video:
        #     json_urls.append("https://www.xuexi.cn/lgdata/"+i.split('!')[1])
        # while len(link) < 20:
        #     choose_json_url = random.choice(json_urls)
        #     choose_json_str = requests.get(choose_json_url).content.decode("utf8")
        #     pattern = r'https://www.xuexi.cn/[^,"]*'
        #     choose_links = re.findall(pattern, choose_json_str, re.I)
        #     if(len(choose_links) >= 5):
        #         choose_sample = random.sample(choose_links, 5)
        #         for c in choose_sample:
        #             link.append(c)
        # random.shuffle(link)
        # return link
    except:
        logger.info("=" * 60)
        logger.info("get_video_links获取失败")
        logger.info("=" * 60)
        raise

```

**Comment by hujinhu** [comment]
> > 你的文章学习有问题吗? 上面的get_article_links方法能看一下吗.
> 
> 我的文章没问题，文件get_links.py这样改应该是文章和视频都可以，原来文章的获取地址中的内容没更新了
> 
> ```
> import logging as logger 
> 
> import requests
> import re
> import random
> import json
> 
> 
> def _get_links(base_url):
>     news_url_json = requests.get(base_url).content.decode(
>         "utf8")
>     news_url = json.loads(news_url_json)["DataSet"]
>     json_urls = []
>     for i in news_url:
>         json_urls.append("https://www.xuexi.cn/lgdata/" + i.split('!')[1])
> 
>     all_news_object = []
>     for url in json_urls:
>         choose_json_str = requests.get(url).content.decode("utf8")
>         all_news_object.extend(json.loads(choose_json_str))
>     new_list = sorted(all_news_object, key=lambda x: x.get("publishTime", "0"), reverse=False)
>     return [news["url"] for news in new_list]
> 
> 
> def get_article_links():
>     try:
>         return _get_links("https://www.xuexi.cn/lgdata/896bddc5f57a423b857a85eb40f98945/72742e3e40c96ade71e42b6e7ed42419.json")
>         # 下面获取文章的地址中文章没有继续更新，导致后面无法完成文章学习
>         # article = requests.get(
>         #     "https://www.xuexi.cn/c06bf4acc7eef6ef0a560328938b5771/data9a3668c13f6e303932b5e0e100fc248b.js").content.decode(
>         #     "utf8")
>         # pattern = r"list\"\:(.+),\"count\"\:"
>         # links = []
>         # list = eval(re.search(pattern, article).group(1))[:20000]
>         # list.reverse()
>         # for i in range(len(list)):
>         #     links.append(list[i]["static_page_url"])
>         # return links
>     except:
>         logger.info("=" * 60)
>         logger.info("get_article_links获取失败")
>         logger.info("=" * 60)
>         raise
> 
> 
> def get_video_links():
>     try:
>         return _get_links("https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json")
> 
>         # 下面的方法只获取了20个地址返回，且是随机获取的，返回的地址可能有之前用过的，不能保证学习满积分
>         # video_json = requests.get("https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json").content.decode("utf8")
>         # video=json.loads(video_json)["DataSet"]
>         # json_urls = []
>         # link = []
>         # for i in video:
>         #     json_urls.append("https://www.xuexi.cn/lgdata/"+i.split('!')[1])
>         # while len(link) < 20:
>         #     choose_json_url = random.choice(json_urls)
>         #     choose_json_str = requests.get(choose_json_url).content.decode("utf8")
>         #     pattern = r'https://www.xuexi.cn/[^,"]*'
>         #     choose_links = re.findall(pattern, choose_json_str, re.I)
>         #     if(len(choose_links) >= 5):
>         #         choose_sample = random.sample(choose_links, 5)
>         #         for c in choose_sample:
>         #             link.append(c)
>         # random.shuffle(link)
>         # return link
>     except:
>         logger.info("=" * 60)
>         logger.info("get_video_links获取失败")
>         logger.info("=" * 60)
>         raise
> ```

感谢, 按你这个文章和视频都可以正常学习了.

**Comment by ZhenIsabel** [comment]
> 

感谢，迎刃而解

**Comment by freshbanana** [comment]
修改了以后报错，启动不了

Traceback (most recent call last):                                                                                                                                                                          
  File "/xuexi/pandalearning.py", line 15, in <module>                                                                                                                                                      
    from pdlearn.article_video import article, video                                                                                                                                                        
  File "/xuexi/pdlearn/article_video.py", line 6, in <module>                                                                                                                                               
    from pdlearn import get_links                                                                                                                                                                           
  File "/xuexi/pdlearn/get_links.py", line 11                                                                                                                                                               
    news_url = json.loads(news_url_json)["DataSet"]                                                                                                                                                         
    ^                                                                                                                                                                                                       
IndentationError: unexpected indent

**Comment by diaodeng** [comment]
> 修改了以后报错，启动不了
> 
> Traceback (most recent call last):                                                                                                                                                                          
>   File "/xuexi/pandalearning.py", line 15, in <module>                                                                                                                                                      
>     from pdlearn.article_video import article, video                                                                                                                                                        
>   File "/xuexi/pdlearn/article_video.py", line 6, in <module>                                                                                                                                               
>     from pdlearn import get_links                                                                                                                                                                           
>   File "/xuexi/pdlearn/get_links.py", line 11                                                                                                                                                               
>     news_url = json.loads(news_url_json)["DataSet"]                                                                                                                                                         
>     ^                                                                                                                                                                                                       
> IndentationError: unexpected indent

你修改时格式错了，缩进没对

**Comment by freshbanana** [comment]
> > 修改了以后报错，启动没了
> > 追溯（最近调用最后）：
> > 文件“/xuexi/pandalearning.py”，第 15 行，在
> > from pdlearn.article_video import article, video
> > 文件“/xuexi/pdlearn/article_video.py”，第 6 行，在
> > from pdlearn import get_links
> > 文件“/xuexi/pdlearn/get_links.py”，第 11 行
> > news_url = json.loads(news_url_json)["DataSet"] 
> > ^ 
> > IndentationError: unexpected indent
> 
> 你修改时格式错了，缩小没有对

后面重新修改，又可以运行了

**Comment by ErrorIce** [comment]
按照楼上的同学的方法解决的问题，感谢分享

**Comment by GOOD-AN** [comment]
按照楼上大佬的方法修改完后，学了两天，今天又一个都不学了

**Comment by GOOD-AN** [comment]
> 按照楼上大佬的方法修改完后，学了两天，今天又一个都不学了

嗯。。。跑第二遍好了

**Comment by diaodeng** [comment]
> 按照楼上大佬的方法修改完后，学了两天，今天又一个都不学了

应该是中间获取到的文章是之前学过的，所以学习不加积分，试着把配置中文章的index改大点

**Comment by fakezhu** [comment]
> > 按照楼上大佬的方法修改完后，学了两天，今天又一个都不学了
> 
> 应该是中间获取到的文章是之前学过的，所以学习不加积分，试着把配置中文章的index改大点

大佬，按照你的方法，前两天可以了，今天网页阅读文章显示白屏，运行窗口不停再往下阅读，实际并未完成阅读

**Comment by r17171709** [comment]
> > > 按照楼上大佬的方法修改完后，学了两天，今天又一个都不学了
> > 
> > 
> > 应该是中间获取到的文章是之前学过的，所以学习不加积分，试着把配置中文章的index改大点
> 
> 大佬，按照你的方法，前两天可以了，今天网页阅读文章显示白屏，运行窗口不停再往下阅读，实际并未完成阅读

文章我是一直都白屏，但是视频是好的，也不知道怎么解决

**Comment by diaodeng** [comment]
学习新闻的地址改成下面的地址目前我这里这正常的，不知道为啥之前学习科学中的新闻很多都不加积分

```import logging as logger 

import requests
import re
import random
import json


def _get_links(base_url):
    news_url_json = requests.get(base_url).content.decode(
        "utf8")
    news_url = json.loads(news_url_json)["DataSet"]
    json_urls = []
    for i in news_url:
        if i.endswith("json"):
            json_urls.append("https://www.xuexi.cn/lgdata/" + i.split('!')[1])

    all_news_object = []
    for url in json_urls:
        choose_json_str = requests.get(url).content.decode("utf8")
        all_news_object.extend(json.loads(choose_json_str))
    new_list = sorted(all_news_object, key=lambda x: x.get("publishTime", "0"), reverse=False)
    return [news["url"] for news in new_list]


def get_article_links():
    try:
        return _get_links("https://www.xuexi.cn/lgdata/72ac54163d26d6677a80b8e21a776cfa/9a3668c13f6e303932b5e0e100fc248b.json")
    except:
        logger.info("=" * 60)
        logger.info("get_article_links获取失败")
        logger.info("=" * 60)
        raise


def get_video_links():
    try:
        return _get_links("https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json")
    except:
        logger.info("=" * 60)
        logger.info("get_video_links获取失败")
        logger.info("=" * 60)
        raise
```

**Comment by diaodeng** [comment]
确实出现文章白屏，还不知道什么情况。。。求大佬们指点

**Comment by diaodeng** [comment]
好像改useragent可以，我改成自己电脑上的浏览器对应的useragent后目前正常

**Comment by hujinhu** [comment]
> 好像改useragent可以，我改成自己电脑上的浏览器对应的useragent后目前正常

请问这个在哪里修改？

**Comment by Nadleeh1988** [comment]
> > 你的文章学习有问题吗? 上面的get_article_links方法能看一下吗.
> 
> 我的文章没问题，文件get_links.py这样改应该是文章和视频都可以，原来文章的获取地址中的内容没更新了
> 
> ```
> import logging as logger 
> 
> import requests
> import re
> import random
> import json
> 
> 
> def _get_links(base_url):
>     news_url_json = requests.get(base_url).content.decode(
>         "utf8")
>     news_url = json.loads(news_url_json)["DataSet"]
>     json_urls = []
>     for i in news_url:
>         json_urls.append("https://www.xuexi.cn/lgdata/" + i.split('!')[1])
> 
>     all_news_object = []
>     for url in json_urls:
>         choose_json_str = requests.get(url).content.decode("utf8")
>         all_news_object.extend(json.loads(choose_json_str))
>     new_list = sorted(all_news_object, key=lambda x: x.get("publishTime", "0"), reverse=False)
>     return [news["url"] for news in new_list]
> 
> 
> def get_article_links():
>     try:
>         return _get_links("https://www.xuexi.cn/lgdata/896bddc5f57a423b857a85eb40f98945/72742e3e40c96ade71e42b6e7ed42419.json")
>         # 下面获取文章的地址中文章没有继续更新，导致后面无法完成文章学习
>         # article = requests.get(
>         #     "https://www.xuexi.cn/c06bf4acc7eef6ef0a560328938b5771/data9a3668c13f6e303932b5e0e100fc248b.js").content.decode(
>         #     "utf8")
>         # pattern = r"list\"\:(.+),\"count\"\:"
>         # links = []
>         # list = eval(re.search(pattern, article).group(1))[:20000]
>         # list.reverse()
>         # for i in range(len(list)):
>         #     links.append(list[i]["static_page_url"])
>         # return links
>     except:
>         logger.info("=" * 60)
>         logger.info("get_article_links获取失败")
>         logger.info("=" * 60)
>         raise
> 
> 
> def get_video_links():
>     try:
>         return _get_links("https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json")
> 
>         # 下面的方法只获取了20个地址返回，且是随机获取的，返回的地址可能有之前用过的，不能保证学习满积分
>         # video_json = requests.get("https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json").content.decode("utf8")
>         # video=json.loads(video_json)["DataSet"]
>         # json_urls = []
>         # link = []
>         # for i in video:
>         #     json_urls.append("https://www.xuexi.cn/lgdata/"+i.split('!')[1])
>         # while len(link) < 20:
>         #     choose_json_url = random.choice(json_urls)
>         #     choose_json_str = requests.get(choose_json_url).content.decode("utf8")
>         #     pattern = r'https://www.xuexi.cn/[^,"]*'
>         #     choose_links = re.findall(pattern, choose_json_str, re.I)
>         #     if(len(choose_links) >= 5):
>         #         choose_sample = random.sample(choose_links, 5)
>         #         for c in choose_sample:
>         #             link.append(c)
>         # random.shuffle(link)
>         # return link
>     except:
>         logger.info("=" * 60)
>         logger.info("get_video_links获取失败")
>         logger.info("=" * 60)
>         raise
> ```

大神，我按照您的代码修改了文件。视频能正常学习了，但是可能因为我文章都学了很多了，导致文章一直没拿满分数，然后就从早上一直跑到晚上在刷文章。。。请问能不能也增加一个数量限制。谢谢大神

**Comment by kt7a** [comment]
> 我的视频不能学习，修改这个文件pdlearn.get_links.py的get_video_links方法
> 
> ```
>         video_json = requests.get(
>             "https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json").content.decode(
>             "utf8")
>         video = json.loads(video_json)["DataSet"]
>         json_urls = []
>         for i in video:
>             json_urls.append("https://www.xuexi.cn/lgdata/" + i.split('!')[1])
> 
>         all_video_object = []
>         for url in json_urls:
>             choose_json_str = requests.get(url).content.decode("utf8")
>             all_video_object.extend(json.loads(choose_json_str))
>         new_list = sorted(all_video_object, key=lambda x: x.get("publishTime", "0"), reverse=False)
>         return [news["url"] for news in new_list]
> ```
> 
> ![image](https://user-images.githubusercontent.com/108243171/217176837-da281543-a7f4-4b44-94a4-3f6d26c89bea.png)

感谢，修改后视频学习已经可以得分了

**Comment by Hany1688** [comment]
有谁共享一下这个修改后的pdlearn.get_links.py吗？

**Comment by wiekern** [comment]
```python
import requests
import re
import random
import json
import logging as logger 

def _get_links(base_url):
    print('_get_links(), ', base_url)
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}
    news_url_json = requests.get(base_url, headers=headers).content.decode(
        "utf8")
    print(news_url_json)
    news_url = json.loads(news_url_json)["DataSet"]
    json_urls = []
    for i in news_url:
        json_urls.append("https://www.xuexi.cn/lgdata/" + i.split('!')[1])
        
    all_news_object = []
    for url in json_urls:
        choose_json_str = requests.get(url, headers=headers).content.decode("utf8")
        all_news_object.extend(json.loads(choose_json_str))
    new_list = sorted(all_news_object, key=lambda x: x.get("publishTime", "0"), reverse=False)
    return [news["url"] for news in new_list]

def get_article_links():
    try:
        return _get_links("https://www.xuexi.cn/lgdata/896bddc5f57a423b857a85eb40f98945/72742e3e40c96ade71e42b6e7ed42419.json")
        # article = requests.get(
        #     "https://www.xuexi.cn/c06bf4acc7eef6ef0a560328938b5771/data9a3668c13f6e303932b5e0e100fc248b.js").content.decode(
        #     "utf8")
        # pattern = r"list\"\:(.+),\"count\"\:"
        # links = []
        # list = eval(re.search(pattern, article).group(1))[:20000]
        # list.reverse()
        # for i in range(len(list)):
        #     links.append(list[i]["static_page_url"])
        # return links
    except:
        print("=" * 60)
        print("get_article_links获取失败")
        print("=" * 60)
        raise


def get_video_links():
    try:
        return _get_links("https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json")

        # 下面的方法只获取了20个地址返回，且是随机获取的，返回的地址可能有之前用过的，不能保证学习满积分
        # video_json = requests.get("https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json").content.decode("utf8")
        # video=json.loads(video_json)["DataSet"]
        # json_urls = []
        # link = []
        # for i in video:
        #     json_urls.append("https://www.xuexi.cn/lgdata/"+i.split('!')[1])
        # while len(link) < 20:
        #     choose_json_url = random.choice(json_urls)
        #     choose_json_str = requests.get(choose_json_url).content.decode("utf8")
        #     pattern = r'https://www.xuexi.cn/[^,"]*'
        #     choose_links = re.findall(pattern, choose_json_str, re.I)
        #     if(len(choose_links) >= 5):
        #         choose_sample = random.sample(choose_links, 5)
        #         for c in choose_sample:
        #             link.append(c)
        # random.shuffle(link)
        # return link
    except:
        logger.info("=" * 60)
        logger.info("get_video_links获取失败")
        logger.info("=" * 60)
        raise
    # try:
    #     video_json = requests.get("https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json").content.decode("utf8")
    #     video=json.loads(video_json)["DataSet"]
    #     json_urls = []
    #     link = []
    #     for i in video:
    #         json_urls.append("https://www.xuexi.cn/lgdata/"+i.split('!')[1])
    #     while len(link) < 20:
    #         choose_json_url = random.choice(json_urls)
    #         choose_json_str = requests.get(choose_json_url).content.decode("utf8")
    #         pattern = r'https://www.xuexi.cn/[^,"]*'
    #         choose_links = re.findall(pattern, choose_json_str, re.I)
    #         if(len(choose_links) >= 5):
    #             choose_sample = random.sample(choose_links, 5)
    #             for c in choose_sample:
    #                 link.append(c)
    #     random.shuffle(link)
    #     return link
    # except:
    #     print("=" * 60)
    #     print("get_video_links获取失败")
    #     print("=" * 60)
    #     raise

```

**Comment by hahahao62** [comment]
您好，您的邮件我已经收到。

**Comment by AmanITal** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fdq236** [comment]
您好，我已收到您发的邮件！待我看后回复！谢谢啦！
                                                                      pcq泉

**Comment by wiekern** [comment]
主要得添加`headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}定义，并传给requests.get(base_url, headers=headers)这个接口即可`

```python
import requests
import re
import random
import json
import logging as logger 

def _get_links(base_url):
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}
    news_url_json = requests.get(base_url, headers=headers).content.decode(
        "utf8")
    news_url = json.loads(news_url_json)["DataSet"]
    json_urls = []
    for i in news_url:
        json_urls.append("https://www.xuexi.cn/lgdata/" + i.split('!')[1])
        
    all_news_object = []
    for url in json_urls:
        choose_json_str = requests.get(url, headers=headers).content.decode("utf8")
        all_news_object.extend(json.loads(choose_json_str))
    new_list = sorted(all_news_object, key=lambda x: x.get("publishTime", "0"), reverse=False)
    return [news["url"] for news in new_list]

def get_article_links():
    try:
        return _get_links("https://www.xuexi.cn/lgdata/896bddc5f57a423b857a85eb40f98945/72742e3e40c96ade71e42b6e7ed42419.json")
        # article = requests.get(
        #     "https://www.xuexi.cn/c06bf4acc7eef6ef0a560328938b5771/data9a3668c13f6e303932b5e0e100fc248b.js").content.decode(
        #     "utf8")
        # pattern = r"list\"\:(.+),\"count\"\:"
        # links = []
        # list = eval(re.search(pattern, article).group(1))[:20000]
        # list.reverse()
        # for i in range(len(list)):
        #     links.append(list[i]["static_page_url"])
        # return links
    except:
        print("=" * 60)
        print("get_article_links获取失败")
        print("=" * 60)
        raise


def get_video_links():
    try:
        return _get_links("https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json")

        # 下面的方法只获取了20个地址返回，且是随机获取的，返回的地址可能有之前用过的，不能保证学习满积分
        # video_json = requests.get("https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json").content.decode("utf8")
        # video=json.loads(video_json)["DataSet"]
        # json_urls = []
        # link = []
        # for i in video:
        #     json_urls.append("https://www.xuexi.cn/lgdata/"+i.split('!')[1])
        # while len(link) < 20:
        #     choose_json_url = random.choice(json_urls)
        #     choose_json_str = requests.get(choose_json_url).content.decode("utf8")
        #     pattern = r'https://www.xuexi.cn/[^,"]*'
        #     choose_links = re.findall(pattern, choose_json_str, re.I)
        #     if(len(choose_links) >= 5):
        #         choose_sample = random.sample(choose_links, 5)
        #         for c in choose_sample:
        #             link.append(c)
        # random.shuffle(link)
        # return link
    except:
        logger.info("=" * 60)
        logger.info("get_video_links获取失败")
        logger.info("=" * 60)
        raise
    # try:
    #     video_json = requests.get("https://www.xuexi.cn/lgdata/4426aa87b0b64ac671c96379a3a8bd26/db086044562a57b441c24f2af1c8e101.json").content.decode("utf8")
    #     video=json.loads(video_json)["DataSet"]
    #     json_urls = []
    #     link = []
    #     for i in video:
    #         json_urls.append("https://www.xuexi.cn/lgdata/"+i.split('!')[1])
    #     while len(link) < 20:
    #         choose_json_url = random.choice(json_urls)
    #         choose_json_str = requests.get(choose_json_url).content.decode("utf8")
    #         pattern = r'https://www.xuexi.cn/[^,"]*'
    #         choose_links = re.findall(pattern, choose_json_str, re.I)
    #         if(len(choose_links) >= 5):
    #             choose_sample = random.sample(choose_links, 5)
    #             for c in choose_sample:
    #                 link.append(c)
    #     random.shuffle(link)
    #     return link
    # except:
    #     print("=" * 60)
    #     print("get_video_links获取失败")
    #     print("=" * 60)
    #     raise
```
