### ISSUE TITLE
运行报错，打开登录二维码时浏览器闪退

### ISSUE THREAD

**Issue by pswgoo** [TechXueXi/TechXueXi#221]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

源码运行

### 软件/源码版本

v20220126

### 系统版本，包含位数

windows10 x64

### 浏览器、驱动版本

chrome 73.0.3683.86

### python版本

python3.7.9 x64

### docker tag版本

不适用docker

### 推送方式

6 网页推送

### 详细描述

============================================================
    我们的网站，GitHub 等页面已经被中国大陆的浏览器加入黑名单，请用谷歌浏览器 chrome 打开我们的站点。
    科技强 guo 官方网站：https://techxuexi.js.org
    Github地址：https://github.com/TechXueXi
使用本项目，必须接受以下内容，否则请立即退出：
    - TechXueXi 仅额外提供给“爱党爱 guo ”且“工作学业繁重”的人
    - 项目开源协议 LGPL-3.0
    - 不得利用本项目盈利
另外，我们建议你参与一个维护劳动法的项目：
https://996.icu/ 或 https://github.com/996icu/996.ICU/blob/master/README_CN.md
============================================================
TechXueXi 现支持以下模式（答题时请值守电脑旁处理少部分不正常的题目）：
--------------------------------------
0 仅登录
1 文章+视频
2           每日答题+每周答题+专项答题
3 文章+视频+每日答题+每周答题+专项答题
4 更改默认用户
5 查看所有用户今日得分情况
6 刷新所有用户登录状态为最新
============================================================
开启： 获取更新信息...
[*] 正在联网获取更新信息...(更新显示不会打断之前输入等操作)
开启： 开始学xi
是否无头模式：False None
当前选择模式：3
============================================================
需要增加新用户，请扫码登录，否则请无视

DevTools listening on ws://127.0.0.1:53248/devtools/browser/3bd61226-5d34-44ba-b7fd-953b8b0b8fc7
欢迎使用 TechXueXi
[*] TechXueXi最新下载地址为 https://github.com/TechXueXi/TechXueXi
[*] 程序版本为：v20220126
[*] 最新版本为：v20220126
正在打开二维码登陆界面,请稍后
Exception in thread 开始学xi:
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\timon\Desktop\xuexi\SourcePackages\pdlearn\threads.py", line 44, in run
    self.func(*self.args)
  File ".\SourcePackages\pandalearning.py", line 73, in start_learn
  File "C:\Users\timon\Desktop\xuexi\SourcePackages\pdlearn\mydriver.py", line 282, in login
    cookie_list = self.get_cookie_from_network(chat_id)
  File "C:\Users\timon\Desktop\xuexi\SourcePackages\pdlearn\mydriver.py", line 150, in get_cookie_from_network
    self.web_log('正在打开二维码登陆界面,请稍后')
  File "C:\Users\timon\Desktop\xuexi\SourcePackages\pdlearn\mydriver.py", line 248, in web_log
    self.web.add_message(send_log)
  File "C:\Users\timon\Desktop\xuexi\SourcePackages\pdlearn\web.py", line 20, in add_message
    web_db.session.rollback()
  File "C:\Python37\lib\site-packages\sqlalchemy\orm\scoping.py", line 1691, in rollback
    return self._proxied.rollback()
  File "C:\Python37\lib\site-packages\sqlalchemy\orm\scoping.py", line 188, in _proxied
    return self.registry()
  File "C:\Python37\lib\site-packages\sqlalchemy\util\_collections.py", line 639, in __call__
    key = self.scopefunc()
  File "C:\Python37\lib\site-packages\flask_sqlalchemy\session.py", line 102, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Python37\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

Exception ignored in: <function Popen.__del__ at 0x000001E8A2001048>
Traceback (most recent call last):
  File "C:\Python37\lib\subprocess.py", line 885, in __del__
    self._internal_poll(_deadstate=_maxsize)
  File "C:\Python37\lib\subprocess.py", line 1245, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] 句柄无效。

**Comment by asaki1986** [comment]
一样的问题，不知道如何解决

需要增加新用户，请扫码登录，否则请无视
欢迎使用 TechXueXi
[*] TechXueXi最新下载地址为 https://github.com/TechXueXi/TechXueXi
[*] 程序版本为：v20220711
[*] 最新稳定版为：v20220126
正在打开二维码登陆界面,请稍后
Exception in thread 开始学xi:
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/Jiang/program/TechXueXi/SourcePackages/pdlearn/threads.py", line 44, in run
    self.func(*self.args)
  File "SourcePackages/pandalearning.py", line 73, in start_learn
    cookies = driver_login.login()
  File "/Users/Jiang/program/TechXueXi/SourcePackages/pdlearn/mydriver.py", line 369, in login
    cookie_list = self.get_cookie_from_network(chat_id)
  File "/Users/Jiang/program/TechXueXi/SourcePackages/pdlearn/mydriver.py", line 237, in get_cookie_from_network
    self.web_log('正在打开二维码登陆界面,请稍后')
  File "/Users/Jiang/program/TechXueXi/SourcePackages/pdlearn/mydriver.py", line 335, in web_log
    self.web.add_message(send_log)
  File "/Users/Jiang/program/TechXueXi/SourcePackages/pdlearn/web.py", line 20, in add_message
    web_db.session.rollback()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 1691, in rollback
    return self._proxied.rollback()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 188, in _proxied
    return self.registry()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 639, in __call__
    key = self.scopefunc()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/flask_sqlalchemy/session.py", line 102, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

**Comment by girlslikeyou** [comment]
我也是这样，快烦死了，一模一样的问题

**Comment by nivranic** [comment]
> 一样的问题，不知道如何解决
> 
> 需要增加新用户，请扫码登录，否则请无视 欢迎使用 TechXueXi [_] TechXueXi最新下载地址为 https://github.com/TechXueXi/TechXueXi [_] 程序版本为：v20220711 [*] 最新稳定版为：v20220126 正在打开二维码登陆界面,请稍后 Exception in thread 开始学xi: Traceback (most recent call last): File "/usr/local/Caskroom/miniconda/base/lib/python3.8/threading.py", line 932, in _bootstrap_inner self.run() File "/Users/Jiang/program/TechXueXi/SourcePackages/pdlearn/threads.py", line 44, in run self.func(*self.args) File "SourcePackages/pandalearning.py", line 73, in start_learn cookies = driver_login.login() File "/Users/Jiang/program/TechXueXi/SourcePackages/pdlearn/mydriver.py", line 369, in login cookie_list = self.get_cookie_from_network(chat_id) File "/Users/Jiang/program/TechXueXi/SourcePackages/pdlearn/mydriver.py", line 237, in get_cookie_from_network self.web_log('正在打开二维码登陆界面,请稍后') File "/Users/Jiang/program/TechXueXi/SourcePackages/pdlearn/mydriver.py", line 335, in web_log self.web.add_message(send_log) File "/Users/Jiang/program/TechXueXi/SourcePackages/pdlearn/web.py", line 20, in add_message web_db.session.rollback() File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 1691, in rollback return self._proxied.rollback() File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 188, in _proxied return self.registry() File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 639, in **call** key = self.scopefunc() File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/flask_sqlalchemy/session.py", line 102, in _app_ctx_id return id(app_ctx._get_current_object()) # type: ignore[attr-defined] File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/werkzeug/local.py", line 513, in _get_current_object raise RuntimeError(unbound_message) from None RuntimeError: Working outside of application context.
> 
> This typically means that you attempted to use functionality that needed the current application. To solve this, set up an application context with app.app_context(). See the documentation for more information.

我也是这样，快烦死了，一模一样的问题

**Comment by nokia5320** [comment]
armv8 docker也无法登录

**Comment by yangxin6** [comment]
我也是这个问题
