### ISSUE TITLE
报错：Working outside of application context

### ISSUE THREAD

**Issue by dasfasdfzkdfklajdfdasd** [TechXueXi/TechXueXi#240]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

源码运行

### 软件/源码版本

20221221

### 系统版本，包含位数

win10 x64

### 浏览器、驱动版本

107.0.5304.88

### python版本

python 3.8（visual studio自带）

### docker tag版本

无

### 推送方式

不使用或不开启推送

### 详细描述

最近重装了系统，之前能正常运行的源码现在扫码页面闪退

DevTools listening on ws://127.0.0.1:51425/devtools/browser/94c58551-edb1-4908-9d11-85dde6aa5ab1
正在打开二维码登陆界面,请稍后
Exception in thread 599330078开始学xi:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\ustcy\Desktop\techxuexi\TechXuexi-master-clone\SourcePackages\pdlearn\threads.py", line 44, in run
    self.func(*self.args)
  File ".\pandalearning.py", line 73, in start_learn
    cookies = driver_login.login()
  File "C:\Users\*\Desktop\techxuexi\TechXuexi-master-clone\SourcePackages\pdlearn\mydriver.py", line 282, in login
    cookie_list = self.get_cookie_from_network(chat_id)
  File "C:\Users\*\Desktop\techxuexi\TechXuexi-master-clone\SourcePackages\pdlearn\mydriver.py", line 150, in get_cookie_from_network
    self.web_log('正在打开二维码登陆界面,请稍后')
  File "C:\Users\*\Desktop\techxuexi\TechXuexi-master-clone\SourcePackages\pdlearn\mydriver.py", line 248, in web_log
    self.web.add_message(send_log)
  File "C:\Users\*\Desktop\techxuexi\TechXuexi-master-clone\SourcePackages\pdlearn\web.py", line 20, in add_message
    web_db.session.rollback()
  File "C:\Users\*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sqlalchemy\orm\scoping.py", line 1706, in rollback
    return self._proxied.rollback()
  File "C:\Users\*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sqlalchemy\orm\scoping.py", line 195, in _proxied
    return self.registry()
  File "C:\Users\*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sqlalchemy\util\_collections.py", line 639, in __call__
    key = self.scopefunc()
  File "C:\Users\*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask_sqlalchemy\session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "C:\Users\*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.

**Comment by Sube3494** [comment]
我也是这个问题，我觉得可能是代码的本身有问题

**Comment by lindentao** [comment]
原因：应用上下文之外的地方访问导致的报错
解决：涉及的代码添加with app.app_context()，参考链接：https://flask-zh.readthedocs.io/appcontext/
