### ISSUE TITLE
每周答题失败

### ISSUE THREAD

**Issue by Carrjiang** [TechXueXi/TechXueXi#67]
### 清单

- 

- [x] 我已经仔细阅读过 README.md  (https://github.com/TechXueXi/TechXueXi/blob/master/README.md)
- [x] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [x] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [x] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**系统版本，包含位数**：Win11 64bit 正式版

**软件/源码版本**：v20210816

**浏览器、驱动版本**：

**python版本**：

**docker版本**：

-----

## 详细描述
答：每周答题失败

## 全部报错
答：

```
============================================================
get_score 获取失败
============================================================
Traceback (most recent call last):
  File "pandalearning.py", line 98, in <module>
  File "pdlearn\answer_question.py", line 401, in weekly
    answer_question(quiz_type, cookies, scores, score_all, quiz_xpath, category_xpath, driver_default=driver_default)
  File "pdlearn\answer_question.py", line 49, in answer_question
    uid = user.get_userId(cookies)
  File "pdlearn\user.py", line 16, in get_userId
    userId, total, scores = score.get_score(cookies)
  File "pdlearn\score.py", line 51, in get_score
    dayScoreDtos = json.loads(score_json)["data"]["dayScoreDtos"]
TypeError: 'NoneType' object is not subscriptable
[45144] Failed to execute script 'pandalearning' due to unhandled exception!
```

## 建议
答：

**Comment by 3xxx** [comment]
请升级到最新版。

**Comment by RayFine95** [comment]
> 请升级到最新版。

也不好使
