### ISSUE TITLE
docker dev72版本，无法生成登录二维码

### ISSUE THREAD

**Issue by jinxin-fu** [TechXueXi/TechXueXi#76]
![image](https://user-images.githubusercontent.com/52962500/138042731-861abfab-5882-491c-9d69-e6d159c0d6a0.png)
![image](https://user-images.githubusercontent.com/52962500/138042742-b760699a-9853-49f8-a6a5-c73afad4dc82.png)

```
需要增加新用户，请扫码登录，否则请无视
正在打开二维码登陆界面,请稍后
检查更新
网络缓慢，请重试
当前网络缓慢...
当前网络缓慢...
二维码将发往机器人...
============================================================
当前网络缓慢...
Exception in thread 开始学xi:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/xuexi/pdlearn/threads.py", line 44, in run
    self.func(*self.args)
  File "/xuexi/pandalearning.py", line 72, in start_learn
    cookies = driver_login.login()
  File "/xuexi/pdlearn/mydriver.py", line 239, in login
    cookie_list = self.get_cookie_from_network()
  File "/xuexi/pdlearn/mydriver.py", line 169, in get_cookie_from_network
    self.sendmsg()
  File "/xuexi/pdlearn/mydriver.py", line 218, in sendmsg
    gl.pushprint(decode_img(qcbase64))
  File "/xuexi/pdlearn/mydriver.py", line 38, in decode_img
    img_b64decode = base64.b64decode(data[data.index(';base64,')+8:])
AttributeError: 'NoneType' object has no attribute 'index'

```

**Comment by fearlessxjdx** [comment]
72是最新的吗？我忘了我是72还是75了，最新的是正常的。

**Comment by jinxin-fu** [comment]
> 72是最新的吗？我忘了我是72还是75了，最新的是正常的。

dockerhub上最新的tag 就是72

**Comment by fearlessxjdx** [comment]
@jinxin-fu 最新的是正常的，你可能漏了配置项没填

**Comment by jinxin-fu** [comment]
> @jinxin-fu 最新的是正常的，你可能漏了配置项没填
docker run -e "AccessToken=xxxx" -e "Secret=xxxxx" -e "Pushmode=1" -e "CRONTIME=*/10 * * * *" -d --name=xuexi1 techxuexi/techxuexi-amd64:dev72
这么起的docker，请教一下还是有其他配置项需要吗

**Comment by jdso1024** [comment]
> CRONTIME
钉钉的话配上schema那个参数

**Comment by jdso1024** [comment]
> > @jinxin-fu 最新的是正常的，你可能漏了配置项没填
> > docker run -e "AccessToken=xxxx" -e "Secret=xxxxx" -e "Pushmode=1" -e "CRONTIME=*/10 * * * *" -d --name=xuexi1 techxuexi/techxuexi-amd64:dev72
> > 这么起的docker，请教一下还是有其他配置项需要吗

钉钉的话配上schema那个参数

**Comment by jinxin-fu** [comment]
> > > @jinxin-fu 最新的是正常的，你可能漏了配置项没填
> > > docker run -e "AccessToken=xxxx" -e "Secret=xxxxx" -e "Pushmode=1" -e "CRONTIME=*/10 * * * *" -d --name=xuexi1 techxuexi/techxuexi-amd64:dev72
> > > 这么起的docker，请教一下还是有其他配置项需要吗
> 
> 钉钉的话配上schema那个参数
 docker run -e "AccessToken=xxxx" -e "Secret=xxxx" -e "Pushmode=1" -e "CRONTIME=*/10 * * * *" -e "Scheme=dtxuexi://appclient/page/study_feeds?url=" -d --name=xuexi3 techxuexi/techxuexi-amd64:dev72
还是提示：
需要增加新用户，请扫码登录，否则请无视
正在打开二维码登陆界面,请稍后


![image](https://user-images.githubusercontent.com/52962500/138247254-c0145fae-9ced-46dd-844d-b9aa47700f52.png)
