### ISSUE TITLE
用git更新后报错 module 'pdlearn' has no attribute 'globalvar'

### ISSUE THREAD

**Issue by bjznl** [TechXueXi/TechXueXi#95]
### 清单

- [x] 我已经仔细阅读过 README.md  (https://github.com/TechXueXi/TechXueXi/blob/master/README.md)
- [x] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [x] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [x] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**系统版本，包含位数**：win10 202h 10942.1288

**软件/源码版本**：20211030

**浏览器、驱动版本**：73.0.3683.86

**python版本**：Python 3.6.5

**docker版本**：

-----

## 详细描述
答：昨天运行的时候提示有更新，我使用windows系统git_pull_一键更新.bat后就发现无法进入程序

## 全部报错
答：D:\nas\TechXueXi-dev\TechXuexi-master-clone\SourcePackages>python ./pandalearning.py   hidden single
Traceback (most recent call last):
  File "./pandalearning.py", line 11, in <module>
    from pdlearn import user
  File "D:\nas\TechXueXi-dev\TechXuexi-master-clone\SourcePackages\pdlearn\user.py", line 1, in <module>
    from pdlearn import globalvar
  File "D:\nas\TechXueXi-dev\TechXuexi-master-clone\SourcePackages\pdlearn\globalvar.py", line 6, in <module>
    from pdlearn.web import WebHandler
  File "D:\nas\TechXueXi-dev\TechXuexi-master-clone\SourcePackages\pdlearn\web.py", line 1, in <module>
    from webserverListener import Message, QrUrl, db
  File "D:\nas\TechXueXi-dev\TechXuexi-master-clone\SourcePackages\webserverListener.py", line 11, in <module>
    import pandalearning as pdl
  File "D:\nas\TechXueXi-dev\TechXuexi-master-clone\SourcePackages\pandalearning.py", line 20, in <module>
    from pdlearn.answer_question import daily, weekly, zhuanxiang
  File "D:\nas\TechXueXi-dev\TechXuexi-master-clone\SourcePackages\pdlearn\answer_question.py", line 14, in <module>
    import pdlearn.globalvar as gl
AttributeError: module 'pdlearn' has no attribute 'globalvar'

## 建议
答：

**Comment by shijinsu** [comment]
我也遇到同样的问题

**Comment by shijinsu** [comment]
需要下载高版本的PYTHON软件包（比如3.7.9），放到CHROME文件夹下，就可以解决问题

**Comment by studylinus** [comment]
> 需要下载高版本的PYTHON软件包（比如3.7.9），放到CHROME文件夹下，就可以解决问题

你好，这个怎么操作？是将python 3.7.9安装到CHROME文件夹下？还是怎么个放法？第一种方法用后并没解决问题，还是我没有理解您的意思，如能及时回复非常感激！

附：我的chrome文件夹在*\TechXueXi-20220126\SourcePackages，包含chrome.exe chromedriver.exe等。
